- category: Subscriptions
  strings:
    - RECURRING

- category: Refunds
  strings:
    - REFUND

- category: Government/Taxes
  strings:
    - " GST/"
    - " PRO/"
    - " FED/"
    - CRA
    - GOV CA
    - "CANADA "

- category: Transfers
  strings:
    - ETRNSFR
    - RECVD
    - "TF "

- category: Steam/Games
  strings:
    - STEAM
    - JAGEX
    - SONY
    - XBOX
    - NINTENDO

- category: Online/Amazon
  strings:
    - AMZN
    - AMZN MKTP
    - AMAZON.CA
    - AMAZON.COM

- category: Gas/Convenience
  strings:
    - SHELL
    - ESSO
    - SHOPPERS DRUG M
    - HASTY MARKET
    - LITTLE SHORT

- category: Groceries
  strings:
    - ZEHRS
    - FRESHCO
    - BULK BARN

- category: Fast Food
  strings:
    - BK
    - MCDONALD'S
    - MCDONALDS
    - PIZZA
    - DAIRY QUEEN
    - TIM HORTONS
    - MARY BROWNS
    - CAESARS
    - WENDY'S

- category: Keyboards
  strings:
    - KEYBOARDS
    - KEEB
    - TYPIST
    - RINGER

- category: Online/Others
  strings:
    - ONLINE
