- category: Subscriptions
  strings:
    - RECURRING

- category: Refunds
  strings:
    - REFUND
    - REVERSAL

- category: Pension
  strings:
    - OMERS

- category: Insurance
  strings:
    - INSURANCE

- category: Cannabis
  strings:
    - CARIBBEAN OXYGEN
    - TOKYO SMOKE
    - CANNABLISS

- category: Government/Taxes
  strings:
    - " GST/"
    - " PRO/"
    - " FED/"
    - CRA
    - GOV CA

- category: Gas
  strings:
    - SHELL
    - ESSO
    - PETRO-CANADA

- category: Convenience
  strings:
    - SHOPPERS DRUG M
    - HASTY MARKET
    - LITTLE SHORT
    - MINI MART

- category: Groceries
  strings:
    - ZEHRS
    - FRESHCO
    - BULK BARN
    - NO FRILLS

- category: Fast Food
  strings:
    - BK
    - MCDONALD'S
    - MCDONALDS
    - PIZZA
    - DAIRY QUEEN
    - TIM HORTONS
    - MARY BROWNS
    - CAESARS
    - WENDY'S
    - ROTI

- category: Alcohol and Spirits
  strings:
    - LCBO
    - BEER

- category: Retail
  strings:
    - DOLLARAMA
    - COSTCO
    - DOLLAR STORE
    - BATH & BODY
    - GIANT TIGER
    - CAMBRIDGE SURPLUS
    - LEN'S MILL
    - SWISS PLUS
    - CANADIAN TIRE
    - VALUE VILLAGE

- category: Transfers
  strings:
    - TRANSFER

- category: Fees
  strings:
    - FEES

- category: Phone
  strings:
    - FREEDOM MOBILE

- category: Online/Others
  strings:
    - ONLINE
