- category: Subscriptions
  strings:
    - RECURRING

- category: Refunds
  strings:
    - REFUND
    - REVERSAL

- category: Government/Taxes
  strings:
    - " GST/"
    - " PRO/"
    - " FED/"
    - CRA
    - GOV CA
    - "CANADA "

- category: Transfers
  strings:
    - ETRNSFR
    - RECVD
    - "TF "

- category: Online/Others
  strings:
    - ONLINE
